### ISSUE TITLE
Template repository 

### ISSUE THREAD

**Issue by jailsonsf** [Juliano-rb/my-express-ts-boilerplate#1]
Olá Juliano,

No github a gente consegue transformar os repositórios em um template
Facilitando na hora de criar um novo projeto usando o projeto template como base
No site do github eles explicam como fazer isso [Template Repository](https://docs.github.com/pt/repositories/creating-and-managing-repositories/creating-a-template-repository).

Acho que seria bastante útil

**Comment by Juliano-rb** [comment]
Transformei em um template. Obrigado @jailsonsf
